name: Deploy to Server

on:
    push:
        branches:
            - main
            - develop

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Production
              if: github.ref == 'refs/heads/main'
              run: |
                  echo "Deploying to production server..."
                  # 실서버 배포 스크립트 실행

            - name: Deploy to Development
              if: github.ref == 'refs/heads/develop'
              run: |
                  echo "Deploying to development server..."
                  # 개발 서버 배포 스크립트 실행
